import styles from '../styles/Home.module.css';
import Head from 'next/head';
import { GetServerSideProps, GetStaticProps, NextPage } from 'next';

import { Dog } from '../data/@types/dogs';
import { TopBar } from '../ui/components/Molecules/TopBar';
import {NavBar} from '../ui/components/Molecules/NavBar';
import { Slide } from '../ui/components/Molecules/Slide';
import { TextSection } from '../ui/components/Atoms/TextSection';
import { Posts } from '../ui/components/Organisms/Posts'

const Home: NextPage<{ characters: Dog[] }> = ({ characters }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBar />
            <NavBar />
         
            <Posts />

        </div>
    )
}
export default Home

export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch('http://localhost:3000/api/dogApi')
    const results: Dog = await res.json()

    return {
        props: {
            characters: results,
        },
    }
}
